# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: CI
on:
  push: ~

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # Note: Use quotes to avoid float cast - especially important if the
          # version number ends with 0!
          - "{{ cookiecutter.python_version }}"
          - "{{ cookiecutter.__python_major }}.{{ cookiecutter.__python_minor | int - 1 }}"
          - "{{ cookiecutter.__python_major }}.{{ cookiecutter.__python_minor | int - 2 }}"

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with=ci
      - name: Run tests
        run: poetry run pytest

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "{{ cookiecutter.python_version }}"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with=ci
      - name: Type checking
        run: poetry run mypy src test

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "{{ cookiecutter.python_version }}"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with=ci
      - name: Check docs build
        run: |
          cd docs
          mkdir -p _static
          poetry run make html
