# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"

  jobs:
    post_create_environment:
      # Install uv
      # https://docs.astral.sh/uv/getting-started/installation/
      - pip install uv
    post_install:
      # Install dependencies with the 'ci' dependency group.
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --group ci

sphinx:
  configuration: docs/conf.py
