[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{ cookiecutter.pypi_project_name }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_short_description }}"
authors = [{ name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}" }]
requires-python = ">={{ cookiecutter.__python_major }}.{{ cookiecutter.__python_minor | int - 2 }}"
readme = "README.rst"
license = "MIT"

# :see: https://pypi.org/classifiers/
keywords = [
]
classifiers = [
]

[project.urls]
Repository = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_project_name }}"
Documentation = "https://{{ cookiecutter.pypi_project_name }}.readthedocs.io/"
Changelog = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_project_name }}/releases"
Issues = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_project_name }}/issues"

[dependency-groups]
# I'm only one person, so to keep from getting overwhelmed, I'm only committing
# to supporting the 3 most recent versions of Python (see docs/adr/001).
dev = [
    "autohooks>=26,<27",
    "autohooks-plugin-black>=23,<24",
    "autohooks-plugin-mypy>=23,<24",
    "autohooks-plugin-pytest>=23,<24",
    "autohooks-plugin-ruff>=25,<26",
    "mypy>=2,<3",
    "pytest>=9,<10",
    "sphinx>=8,<9",
    "sphinx_rtd_theme>=3,<4",
    "tox>=4,<5",
    "tox-uv>=1,<2",
]

# Used by GitHub Actions and ReadTheDocs.
ci = [
    "mypy>=2,<3",
    "pytest>=9,<10",
    "sphinx>=8,<9",
    "sphinx_rtd_theme>=3,<4",
    "tox-uv>=1,<2",
]

[tool.autohooks]
mode = "pythonpath"
pre-commit = [
    "autohooks.plugins.black",
    "autohooks.plugins.mypy",
    "autohooks.plugins.pytest",
    "autohooks.plugins.ruff",
]

[tool.hatch.build.targets.sdist]
include = [
    "src/{{ cookiecutter.package_name }}",
    "LICENCE.txt",
    "docs",
    "test",
]
exclude = ["docs/_build"]

[tool.hatch.build.targets.wheel]
include = ["src/{{ cookiecutter.package_name }}"]
exclude = ["docs/_build"]

[tool.hatch.build.targets.wheel.sources]
"src/{{ cookiecutter.package_name }}" = "{{ cookiecutter.package_name }}"

[tool.mypy]
strict = true

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.tox]
env_list = [
    "py{{ cookiecutter.__python_major }}{{ cookiecutter.__python_minor }}",
    "py{{ cookiecutter.__python_major }}{{ cookiecutter.__python_minor | int - 1 }}",
    "py{{ cookiecutter.__python_major }}{{ cookiecutter.__python_minor | int - 2 }}",
]

[tool.tox.env_run_base]
commands = [
    ["pytest"],
    ["mypy", "src", "test"],
]
runner = "uv-venv-lock-runner"
